backend:
  name: github
  repo: v08nike/cloudflare-cms-app # Required; GitHub repo name
  branch: main # Required; default branch
  auth:
    provider: github
    clientId: Ov23li55q7zj0NT2kUnU
    clientSecret: add991174d8f1ae72e140877961180429510439f
media_folder: "public/uploads" # Folder where media files will be stored
collections:
  - name: "posts" # Used in routes like /admin/collections/posts
    label: "Posts"
    folder: "posts" # The path to the folder where posts are stored
    create: true # Allow users to create new posts
    slug: "{{slug}}" # Custom URL Slug for each post
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }