backend:
  name: github
  repo: v08nike/cloudflare-cms-app # Required; GitHub repo name
  branch: main # Required; default branch
  site_domain: http://localhost:3000
  base_url: http://localhost:3000
  auth_endpoint: /api/auth
  auth_scope: repo
media_folder: "public/uploads" # Folder where media files will be stored
public_folder: "public/"
collections:
  - name: "posts" # Used in routes like /admin/collections/posts
    label: "Posts"
    folder: "posts" # The path to the folder where posts are stored
    create: true # Allow users to create new posts
    slug: "{{slug}}" # Custom URL Slug for each post
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: true }
      - { label: "Created At", name: "created_at", widget: "datetime", required: true, default: "now", date_format: "YYYY-MM-DD HH:mm:ss" }
      - { label: "Updated At", name: "updated_at", widget: "datetime", required: true, default: "now", date_format: "YYYY-MM-DD HH:mm:ss" }
