backend:
  name: github
  repo: v08nike/cloudflare-cms-app # Required; GitHub repo name
  branch: main # Required; default branch
  site_domain: https://cloudflare-cms-app.pages.dev/
  base_url: https://cloudflare-cms-app.pages.dev/
  auth_endpoint: /api/auth
  auth_scope: repo
media_folder: "public/uploads" # Folder where media files will be stored
public_folder: "public/"
collections:
  - name: "posts" # Used in routes like /admin/collections/posts
    label: "Posts"
    folder: "posts" # The path to the folder where posts are stored
    create: true # Allow users to create new posts
    slug: "{{slug}}" # Custom URL Slug for each post
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
